### ISSUE TITLE
New Site Structure / Design Architecture

### ISSUE THREAD

**Issue by ksheedlo** [luvit/luvit.io#1]
Yesterday we discussed redesigning both the luvit.io homepage (at https://luvit.io) and blog (to be deployed at https://blog.luvit.io) in the same layout with the same styling. We need to come up with a workflow for how to share common assets such as compiled CSS files, images, templates, etc. between the blog and the homepage. There are a couple of different ways we could do this. I recommend starting a new repo for common assets, perhaps at https://github.com/luvit/site-design. Then we can use Bower to track the site-design repo both here and in the eventual home page repo.

**Comment by ksheedlo** [comment]
I have a repo with a mockup that I'd like to sooner or later transfer over to the Luvit organization. For now, it's at https://github.com/ksheedlo/site-design.

Here's a screenshot of the working home page design.

![screen shot 2015-03-14 at 2 33 52 pm](https://cloud.githubusercontent.com/assets/1271410/6653649/9c3e8d1c-ca57-11e4-8839-647b2d35a47e.png)

**Comment by rphillips** [comment]
I think this will be great! Thanks for the help Ken.

Reference to the Logo work: https://github.com/luvit/logo

**Comment by rphillips** [comment]
Some examples to hook people in would be wise.Thoughts?

**Comment by ksheedlo** [comment]
@rphillips: code samples? We'll have those. The color scheme needs to be redone from the current homepage, since having code in colors that are inverted from the surrounding copy hurts readability.

**Comment by ksheedlo** [comment]
@creationix can you make a version of the logo that's white on transparent? I don't have a good vector graphics editor on my machine at the moment or I would do it. Something like this:

![luvit-logo-white](https://cloud.githubusercontent.com/assets/1271410/6653995/2ae1fd1c-ca65-11e4-8ee5-09d910e73d0f.png)

Otherwise the new logo isn't going to work on a blue background and we'll have to change some things around.

(I realize this is impossible to see on github. There is still an outline around the heart, but I changed it from blue to white. Best to just download it.)

**Comment by ksheedlo** [comment]
Screenshot with code samples

![screen shot 2015-03-14 at 8 40 28 pm](https://cloud.githubusercontent.com/assets/1271410/6654580/7a4cabde-ca8a-11e4-9fff-38082a98a896.png)

**Comment by voronianski** [comment]
@ksheedlo @rphillips @creationix 

It's great to see such discussion related to Luvit!

I really love what Facebook does on their open-sourced projects, docs and landing pages look very pretty and easy to follow, some of the examples:
- [Immutable.js](http://facebook.github.io/immutable-js)
- [Flow](http://flowtype.org/docs)

IMHO @ksheedlo's screenshot looks a bit of too much bootstrapish so I would like to propose to make some changes in it in order to bring more unique feel to Luvit.

Logo looks nice :+1:

**Comment by creationix** [comment]
Fwiw, while I was waiting on @ksheedlo's mockups, I did a design of my own in this repo.  You can see a quick preview at luvit.io:9090.

Ken, I'll get you a white version as soon as I'm at my desk.  My linux box is much better for working with inkscape, though you can install it on your mac if you're impatient.  I think it still requires X11 to run.

**Comment by ksheedlo** [comment]
> ksheedlo's screenshot looks a bit of too much bootstrapish

Agreed, but I think it's mainly the Helvetica that's the problem there. That can and should be changed. I'm looking for a sans that fits well with the message that we want to deliver, but it's going to take some time and discovery on my part.

**Comment by creationix** [comment]
New versions of the logo at https://github.com/luvit/logo

**Comment by creationix** [comment]
I'm using "Ubuntu" 400 and 700 weight in mine with "Ubuntu Mono" for code.
I find it to be a nice font in it's own right.

Also the font in the logo is "Ubuntu" 700 weight I believe.

**Comment by ksheedlo** [comment]
Here's the prototype with the updated logo.

![screen shot 2015-03-16 at 11 03 53 pm](https://cloud.githubusercontent.com/assets/1271410/6682141/d7f64db0-cc30-11e4-9d7e-2e27d71b544e.png)

I tried putting it in the brand link in the upper left hand corner as well, but the shadows looked ugly after scaling that far down. If we want to put the logo in the brand corner, we should adjust it to be flatter and more stylized, otherwise it's just too busy to do well in a small space.

**Comment by ksheedlo** [comment]
Take a look at this prototype. It's using Proxima Nova instead of Helvetica for the headings and body text.

![screen shot 2015-03-16 at 11 27 58 pm](https://cloud.githubusercontent.com/assets/1271410/6682326/572dc9fc-cc34-11e4-9256-d5aa8b4b9e42.png)

Cool, curvy, geometric letters :heart_eyes:

**Comment by ksheedlo** [comment]
I also want to try the prototype in
- [ ] Freight Sans
- [ ] Open Sans
- [ ] Ubuntu
- [ ] Myriad Pro
- [ ] Europa

**Comment by rphillips** [comment]
wow. the Proxima Nova looks sharp.

**Comment by creationix** [comment]
@ksheedlo I added a flat version for tiny logos to the logo repo, preview at https://github.com/luvit/logo/blob/master/tiny-logo.svg

**Comment by creationix** [comment]
@ksheedlo I've pushed what I have so far to the live site.  Your feedback has been extremely helpful.  I don't have more days to spend tweaking the style.  It is already much better than what we had before.

https://luvit.io/

Thanks again.
