### ISSUE TITLE
Document server in MOTD

### ISSUE THREAD

**Issue by creationix** [luvit/luvit.io#10]
Add description of services (locations and commands) in MOTD.

**Comment by rdw-software** [comment]
Is this issue still relevant? If not, close? Otherwise, needs more details because I doubt anyone knows what it's referring to :)

**Comment by squeek502** [comment]
My guess is that this was referring to the lit server, which is documented here: 

https://github.com/luvit/lit/blob/259ccde59c5dbda9b319c6898eb41cee55e5c16c/libs/api.lua#L19-L73

https://github.com/luvit/lit/blob/259ccde59c5dbda9b319c6898eb41cee55e5c16c/libs/README#L87-L136

**Comment by creationix** [comment]
There was once a time where many people maintained the production servers and the idea was to print instructions for anyone when they logged in via SSH.  Closing this is fine.
