### ISSUE TITLE
blog down ?

### ISSUE THREAD

**Issue by lduboeuf** [luvit/luvit.io#13]
hi,
anything wrong with Luvit.io blog page ?
i got a " Looks like there aren't any blog articles published here yet. Come back later."

**Comment by creationix** [comment]
That's strange, it's the same process as the rest of luvit.io.  I must have a regression somewhere.

**Comment by creationix** [comment]
Thanks for the report.  There was a breaking change in luv a while back and I thought I fixed all the places that were affected by it.  Since luv is an implicit dependency, my old code was running new luv and broke.

It's fixed and working now.

**Comment by lduboeuf** [comment]
:+1:
