### ISSUE TITLE
lit.luvit.io is down

### ISSUE THREAD

**Issue by skwerlman** [luvit/luvit.io#16]
All requests to lit.luvit.io return http 502 (bad gateway).

**Comment by carlosconejo-wc** [comment]
same here, getting a 502 from lit.luvit.io

**Comment by creationix** [comment]
Yeah, not sure what happened there.  I restarted the service this morning and it appears to still be up.

Sorry for the trouble.

**Comment by 5at** [comment]
it is still down

**Comment by rphillips** [comment]
It's up again. I also tweaked the status script to perhaps fix the autorestart

**Comment by creationix** [comment]
I'm assuming the main https://luvit.io/ hasn't gone down since I switched it to a static site?

Since lit.luvit.io is a dynamic service, what we really need is someone to spend the time to find the root cause and fix whatever resource leak keeps crashing it.

**Comment by rphillips** [comment]
@creationix i did fix the restart script, so it might actually restart the lit service now

**Comment by creationix** [comment]
Cool, thanks, that should work for now.
