### ISSUE TITLE
Luvit is not installing

### ISSUE THREAD

**Issue by YahyaAbolsaad** [luvit/luvit.io#29]
I tried to install luvit but it is not working, it is not showing any errors either.
![image](https://user-images.githubusercontent.com/73656813/97632900-de4e5400-1a3b-11eb-8f21-e12181ee8dd6.png)

I disabled my antivirus, and tried to download it from [Releases](https://github.com/luvit/luvi/releases) but is not working, a black window that looks like the cmd prompt shows up for a second then it fades away.

**Comment by squeek502** [comment]
You should see output from the install command, so something is going wrong there. Here's what I get (truncated):

```
Downloading https://github.com/luvit/luvi/releases/download/v2.10.1/luvi-regular-Windows-amd64.exe to luvi.exe
Downloading https://lit.luvit.io/packages/luvit/lit/v3.8.1.zip to lit.zip
lit version: 3.8.1
luvi version: v2.10.1
command: make lit.zip lit.exe luvi.exe
load config: C:\Users\Ryan\AppData\Roaming\litconfig
compiling filter: ** excludes by default (first rule is positive)
including: commands/README
including: commands/add.lua
including: commands/auth.lua
...
```

If that doesn't work, you can [see what get-lit.ps1](https://github.com/luvit/lit/blob/master/get-lit.ps1) is doing here. To do the same steps manually, you could:

- Download [the latest Luvi .exe from here](https://github.com/luvit/luvi/releases/latest) (you'd probably want the `-regular-Windows-amd64.exe` variant)
- Rename the downloaded Luvi .exe to `luvi.exe`
- Download [the latest Lit .zip here](https://lit.luvit.io/packages/luvit/lit/latest.zip) and rename it to `lit.zip`
- Run `luvi lit.zip -- make lit.zip lit.exe luvi.exe` from the command line in the folder where you downloaded `luvi.exe` and `lit.zip` to
- Then run `lit make lit://luvit/luvit luvit.exe luvi.exe` to build Luvit

---

P.S. about "a black window that looks like the cmd prompt shows up for a second then it fades away": Lit/Luvi/Luvit are all command-line applications meaning you need to run them from within an existing command prompt.

**Comment by YahyaAbolsaad** [comment]
> You should see output from the install command, so something is going wrong there. Here's what I get (truncated):
> 
> ```
> Downloading https://github.com/luvit/luvi/releases/download/v2.10.1/luvi-regular-Windows-amd64.exe to luvi.exe
> Downloading https://lit.luvit.io/packages/luvit/lit/v3.8.1.zip to lit.zip
> lit version: 3.8.1
> luvi version: v2.10.1
> command: make lit.zip lit.exe luvi.exe
> load config: C:\Users\Ryan\AppData\Roaming\litconfig
> compiling filter: ** excludes by default (first rule is positive)
> including: commands/README
> including: commands/add.lua
> including: commands/auth.lua
> ...
> ```
> 
> If that doesn't work, you can [see what get-lit.ps1](https://github.com/luvit/lit/blob/master/get-lit.ps1) is doing here. To do the same steps manually, you could:
> 
> * Download [the latest Luvi .exe from here](https://github.com/luvit/luvi/releases/latest) (you'd probably want the `-regular-Windows-amd64.exe` variant)
> * Rename the downloaded Luvi .exe to `luvi.exe`
> * Download [the latest Lit .zip here](https://lit.luvit.io/packages/luvit/lit/latest.zip) and rename it to `lit.zip`
> * Run `luvi lit.zip -- make lit.zip lit.exe luvi.exe` from the command line in the folder where you downloaded `luvi.exe` and `lit.zip` to
> * Then run `lit make lit://luvit/luvit luvit.exe luvi.exe` to build Luvit
> 
> P.S. about "a black window that looks like the cmd prompt shows up for a second then it fades away": Lit/Luvi/Luvit are all command-line applications meaning you need to run them from within an existing command prompt.

@squeek502 I downloaded both and put them in the same folder and rank the command, this is what happened
![image](https://user-images.githubusercontent.com/73656813/97646173-b371f900-1a57-11eb-8ac5-a4cc7b20f4f6.png)

**Comment by YahyaAbolsaad** [comment]
And I tried running it in the powershell but it isn't working
![image](https://user-images.githubusercontent.com/73656813/97647451-f41f4180-1a5a-11eb-914a-c5636eb597df.png)

**Comment by squeek502** [comment]
> I downloaded both and put them in the same folder and rank the command

`luvi.exe` and `lit.zip` are in `E:\Bot\Test`?

> And I tried running it in the powershell but it isn't working

You could try again, sometimes the Lit server errors.

**Comment by YahyaAbolsaad** [comment]
> > I downloaded both and put them in the same folder and rank the command
> 
> `luvi.exe` and `lit.zip` are in `E:\Bot\Test`?
 Yes they are.
> > And I tried running it in the powershell but it isn't working
> 
> You could try again, sometimes the Lit server errors.
Alright, I will give it a try in a bit.

**Comment by YahyaAbolsaad** [comment]
I manually installed `lit.zip` and `luvi.exe` and ran 
```# Create lit.exe using lit
Start-Process ".\luvi.exe" -ArgumentList "lit.zip -- make lit.zip lit.exe luvi.exe" -Wait -NoNewWindow
# Cleanup
Remove-Item "lit.zip"
# Create luvit using lit
Start-Process ".\lit.exe" -ArgumentList "make lit://luvit/luvit luvit.exe luvi.exe" -Wait -NoNewWindow
```
in powershell and it worked,
